# Generated by Django 2.1.3 on 2018-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_casa', models.IntegerField()),
                ('time_fora', models.IntegerField()),
                ('gol_tm_casa', models.IntegerField()),
                ('gol_tm_fora', models.IntegerField()),
                ('data', models.DateField()),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
