# Generated by Django 2.1.3 on 2018-11-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='fundacao',
            field=models.DateField(),
        ),
    ]
