# Generated by Django 2.1.3 on 2018-11-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0002_auto_20181114_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='camp', serialize=False, to='campeonato.Campeonato'),
        ),
    ]
