# Generated by Django 2.1.3 on 2018-11-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0003_auto_20181114_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='org', serialize=False, to='campeonato.Campeonato'),
        ),
    ]
