# Generated by Django 2.1.3 on 2018-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_auto_20181114_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='organizador',
            field=models.IntegerField(),
        ),
    ]
