# Generated by Django 2.1.3 on 2018-11-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_auto_20181114_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos', to='organizador.Organizador'),
        ),
    ]
