# Generated by Django 2.1.3 on 2018-11-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonato', '0005_auto_20181114_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criacao', models.DateField()),
                ('pontuacao', models.IntegerField()),
                ('escudo', models.FileField(upload_to='')),
                ('hino', models.FileField(upload_to='')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to='campeonato.Campeonato')),
            ],
        ),
    ]
